name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Amit-Chandra

      - name: Push to Branch
        run: |
          git config --global user.email "ask.amitchandra@gmail.com"
          git config --global user.name "Amit Chandra"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake contribution grid"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
